---
name: DevSecOps Pipeline
on:
  workflow_dispatch:
jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml
    secrets: inherit
  dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml
  docker-scan:
    uses: ./.github/workflows/docker-lint.yml
  build:
    needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
  scan-image:
    needs: [build]
    uses: ./.github/workflows/image-scan.yml
    secrets: inherit
