---
name: Image Scan
on:
  workflow_call:
jobs:
  image-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: scan image
        uses: aquasecurity/trivy-action@0.33.1
        with:
          severity: 'CRITICAL'
          exit-code: '1'
